### ISSUE TITLE
Link to logging sinks other than env_logger in the README/crate docs

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#115]
A major purpose of the `log` crate is to be flexible wrt to the logger implementation! We should link to popular implementations of loggers in addition to other loggers than `env_logger`. This'll hopefully dispel the notion that env_logger is "the logger implementation" and is instead just "a logger implementation".

**Comment by budziq** [comment]
@alexcrichton these seam to be the most popular logger implementations based on `log`
- https://crates.io/crates/syslog
- https://crates.io/crates/log4rs
- https://crates.io/crates/fern
- https://crates.io/crates/slog-stdlog
- https://crates.io/crates/simple_logger
- https://crates.io/crates/simplelog
- https://crates.io/crates/slog-envlogger
- https://crates.io/crates/pretty_env_logger
- https://crates.io/crates/stderrlog
- https://crates.io/crates/flexi_logger
- https://crates.io/crates/loggerv

While some like - slog-envlogger, slog-stdlog are adapters for otherwise incompatible logging framework others are simple extensions of the env_logger idea scratching a specific itch.

Should we limit the list to only 5 most popular / interesting / diverse?

**Comment by alexcrichton** [comment]
Thanks for ievestigating! I'd be fine with listing all personally, @sfackler do you have thoughts?

**Comment by sfackler** [comment]
Yeah - I'd maybe divide them into broad categories to help people figure out which one makes sense for them. You have adaptors for other frameworks like slog-stdlog, super simple things, and then more heavyweight/configurable things like fern and log4rs.

**Comment by dtolnay** [comment]
Fixed in #188.
