### ISSUE TITLE
Remove env_logger from this repository

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/log#145]
Let's find a suitable maintainer and move it out of the `log` repository itself. While still a high quality logger that we'd likely want to recommend, it may benefit from spreading out the maintenance burden! Tons of possible features were mentioned for `env_logger` on the [evaluation thread](https://internals.rust-lang.org/t/crate-evaluation-for-2017-05-16-log/5185/50) and may wish to make their way to the new repository.

**EDIT**

PRs that need to be resubmitted to the new repo:

- [x] #113 
- [x] #219

**Comment by sebasmagri** [comment]
Hey @alexcrichton, I've started to work on this split at sebasmagri/env_logger.

I'll review the features mentioned in the evaluation thread and check out the API guidelines for the new repo.

For now, I'm pointing it to `log`'s git repo since there where some breaking changes in its enums. What would be the plan in `log`'s side to make a stable dep for `env_logger`?

**Comment by sebasmagri** [comment]
@alexcrichton @sfackler by @brson suggestion, I've added you guys as collaborators in the new repo.
Is there any particular improvement that should be done for it?

**Comment by brson** [comment]
Thanks @sebasmagri!

**Comment by jethrogb** [comment]
How do you want to handle outstanding PRs?

**Comment by sebasmagri** [comment]
@jethrogb ideally the changes should be resubmitted to the new repo... Can you please point me to those?

**Comment by brson** [comment]
Seems like we need to make some decisions about this - are we going to do a handover here, and how?

If we're confident doing it then it seems like we should maybe land the outstanding PRs, remove env_logger from this repo, and maybe reimport that state into @sebasmagri's.

cc @sfackler @alexcrichton

**Comment by sebasmagri** [comment]
For the record, the open PRs that touch `env_logger` are #203 (though this is already open in the new repo as well), #196 which is just about adding a noop `flush` method to env_logger's `Logger`, and #113 which is not yet defined as per @dtolnay's feedback.

There has no been further changes to `env_logger` since I transplanted it.

**Comment by sfackler** [comment]
I would love to give env-logger over to a motivated maintainer.

**Comment by mjkillough** [comment]
#200 has also made a small change to env_logger in this repo and #196 has now been merged. I've made both changes to the forked env_logger here: sebasmagri/env_logger#15.

**Comment by alexcrichton** [comment]
@sebasmagri have you logged into crates.io yet? I tried adding you as an owner but it said you weren't registered :(

**Comment by sebasmagri** [comment]
@alexcrichton I hadn't, you should be able to find me now.

**Comment by alexcrichton** [comment]
@sebasmagri ok you're added as an owner, as soon as everything's sorted away I think we can just have a PR to remove it from this repo.

**Comment by KodrAus** [comment]
I'll leave this open until we've got the current set of PRs against `env_logger` ported over:

- #113 
- #219
