### ISSUE TITLE
Inspiration from logxi?

### ISSUE THREAD

**Issue by lunemec** [rust-lang-nursery/log#97]
Hi,
I just wanted to present to you this Golang library: https://github.com/mgutz/logxi. I'm using it in my Go projects and I find it awesome.

I considered writing something like it for rust, but since there is already logging library, I just wanted you to take a look and consider adding some features here...

Examples:
* automatic stdout/file detection for dev/prod usage
* dev logging with nicely formatted and colored output
* logging to file in parseable format - JSON
* changing logged levels by ENV variable before running the program

And maybe others?
Thank you.

**Comment by dpc** [comment]
Why not just use slog-rs?

**Comment by sfackler** [comment]
The log crate is a *facade* - it provides an interface for crates to log messages, and allows application authors to chose which actual logger implementation they would like to use. You could create a logxi-like logger implementation; see https://doc.rust-lang.org/log/log/index.html#logger-implementations for more information on that.

**Comment by lunemec** [comment]
@dpc slog-rs looks promising, but I wanted THE logging solution. Because I hate JS-like style of having 10 different libraries that all do something but none does it all. Performance is not my primary concern in most Go applications, but in Rust it might be.

@sfackler yes, that would be a solution, however I was looking at having out-of-the-box rust solution, that would be fast and suit most usecases.

Also as a side note, this is true for Go, Python and Rust alike. There are several different libraries that all log as JSON (or other structured format that can be easily machine-parsed), but none are the same. Imagine you have projects in all these languages (which is mostly true with larger companies) and you have to write same tools N times - for each language, but with minor differences - like different syntax, or same JSON but different base field names (time/t_ .. etc). This is really anoying and I would very much appreciate having the same format and tooling for all the languages. But we don't live in such a world (yet) :)

**Comment by dpc** [comment]
@lunemec What do you mean by "THE logging solution"? slog can do everything, since you can add any functionality to it and reuse existing pieces. It is both the *facade* like `log` (but supporting structured logging) and set of modular features. 

`slog` does not even forces name of keys or anything. It's not practical to herd multiple languages into using same logging. It's not even desirable: different organizations, etc. will have different requirements etc. That's why `log` is just a *facade* and you can build your backend for it for your organization. *slog* goes one step further and introduced `trait Drain` that is a building block for logging feature. What you can have is a well specified logging serialization standard : I'm aware of bunyan, which `slog` support via `slog-bunyan`.

**Comment by sfackler** [comment]
There are a variety of logging implementations to chose from in Rust just as there are in Go, ranging from something simple like `env_logger`, to logback style configurability like `log4rs`, to structured logging like `slog`. Something similar enough to logxi to suit your needs may or may not exist, but it doesn't seem like there's anything actionable on the log crate itself.

**Comment by lunemec** [comment]
Thank you for the ideas, I'll try these libraries out :)
